### ISSUE TITLE
現状と課題

### ISSUE THREAD

**Issue by porolakka** [porolakka/aller#12]
### officeに原稿があります。
https://onedrive.live.com/redir?resid=C43056F99B68948C!4874&authkey=!ABbIMHPPDcNPlE0&ithint=file%2cdocx

### 他のページの作成
https://onedrive.live.com/redir?resid=C43056F99B68948C!4874&authkey=!ABbIMHPPDcNPlE0&ithint=file%2cdocx

#### 役割分担
原稿ページのうち、
@itaghiroa （保育士への取材メモ） 
@takepull （イベント開催予定） 
作成お願いします

### ナビとかルーセルの間隔が開く
@cyaro 修正お願いします。 branch anada-nav の作成をお願いします。

↓参考に
http://getbootstrap.com/components/#navbar
http://shared-blog.kddi-web.com/activity/200
http://ascii.jp/elem/000/000/922/922180/
http://blog.livedoor.jp/kmiwa_project/archives/1011015682.html
http://designup.jp/bootstrap3-navbar-189/

### 見出しのデザイン（左端、弧を描く部分）を作る
@porolakka 修正します。branch akira-mi を作成します。

**Comment by cyaro** [comment]
担当　どうしましょうか？

**Comment by porolakka** [comment]
役割分担、ザックリと決めました。
