### ISSUE TITLE
コーディング各担当

### ISSUE THREAD

**Issue by itaaa** [porolakka/aller#9]
竹中さん：ヘッダーとグロナビ
落合くん：3カラムコンテンツとコピーライト
板垣：スライドショー部分

穴田くんの担当は来た時に要相談

**Comment by porolakka** [comment]
本日は板垣さん担当分を穴田くん担当でよろしくお願いします。

竹中さん：ヘッダーとグロナビ
落合くん：3カラムコンテンツとコピーライト
穴田くん：スライドショー部分
